### ISSUE TITLE
FAQ Module Computers

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/FabMob#13]
### How to log in ?
Mot de passe
c'est le même mot de passe qu'au OpenFab.

### What if the computer doesn't start up ?
Branchez-le avec le prise de courant dans l'écran pendent une bonne 10 min.

### What is inside ?
![img_2122](https://user-images.githubusercontent.com/12049360/40847385-850cdac8-65bc-11e8-8966-3a63422befb7.png)

- 7x dell latitude
- 7x power supply dell
- 1x lenovo helix2
- 1x power supply lenovo
- ?x souris usb
- 1x tablettes graphique "bamboo wacom" + câble USB

**Comment by nicolasdb** [comment]
new link, 
https://github.com/openfab-lab/FabMob/blob/master/FAQ/computers-module.md
