### ISSUE TITLE
photos facturation smart

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/FabMob#23]
![smarttt](https://user-images.githubusercontent.com/25649502/53566581-df3f2c00-3b5c-11e9-9d47-47543ebd1927.png)
![smart2](https://user-images.githubusercontent.com/25649502/53566583-df3f2c00-3b5c-11e9-86f5-ef444ddd6dd0.png)

**Comment by nicolasdb** [comment]
Il manque les infos de facturation de Synto
```
Syntonie ASBL
TVA: BE0844983628
23 rue de l'etang
5575 Willerzie
Belgium
```

**Comment by DewiBrunet** [comment]
ok, mis à jour dans https://github.com/openfab-lab/FabMob/blob/master/FAQ/FAQ_facturation.md
