### ISSUE TITLE
Update OpenFab_Réunion Coord 14-05-18

### ISSUE THREAD

**Issue by DewiBrunet** [openfab-lab/FabMob#3]
Rapide update suite à la dernière réunion de coordination.
Il y a un compte rendu détaillé qui arrive mais ci-dessous les éléments qui nous concernent : 

1) Déco TechTruck
- Fournir des trucs cassés qui font "tech" (-->bonne occasion de se débarrasser de certains trucs qui traîne à OpenFab?)
- Fournir des photos (pour la tablette) ou objets de projets qu'on aurait fait (--> support graine de Paris? les brols qui sont dans notre "espace vitrine"?)

2) Syntonie assujettie à la TVA

- Ca change quelque chose par rapport à d'autres partenaires non assujettis?

3) Budget en plus
- à priori ce sera mis sur du marketing/comm (flyer, affiche, vidéo...), sur de la création de contenu et sur les assurances mais si on vois d'autres trucs faut le dire

4) Convention
- Pour fin Mai faut la relire (dans Budget/Compta -> Dossier Innoviris), surtout vérifier les apports & besoins de Syntonie

5) Trombi du site
- Pour chaque animateur/coordinateur : envoyer un portrait + quelques lignes (formation, compétence, ce qu'on aime)

6) Softwares
- Un tableau avec tous les softwares nécessaire à avoir installé (apparemment c'est déjà fait mais pas forcément super clair?)

7) Chèque Fablab
- Pas d'avancement la dessus... j'ai pourtant insisté plusieurs fois sur l'importance de ce point, la coordination est d'accord mais c'est aux trois fablab de se réunir (mais j'ai pas vraiment senti un intérêt de leur part, en partie p-e car Imal est un peu en réorganisation avec le départ de Luc). Margot m'indique qu'elle est prête à assister à cette réunion mais c'est bien à nous de lancer l'affaire.

**Comment by nicolasdb** [comment]
1. Déco truck. on peut dire que c'est fait ça non?
2. TVA synto. 
![image](https://user-images.githubusercontent.com/12049360/51126157-b835d080-1822-11e9-8e45-182d2f02e547.png)
La différence c'est qu'on dépense moins, parce qu'un partenaire qui paye 4520€ de son budget ne récupère pas la TVA. Nous oui, donc on ne justifie que 3840€ de notre budget Innoviris car on récupère plus tard la différence en TVA. 
Si on récupère TVA et qu'en plus Innovris nous remboursait tout, ça serai de l'entourloupe comptable. C'est le mal. 
**Bonus pour nous donc.** Au lieu de 100k, on doit en dépenser presque 120k. On est loin du compte mais c'est surtout sur les prestations qu'on paye bcp de TVA. On peut potentiellement payer plus de presta 👍 
3. budget en plus, c'est réglé aussi ça non?
4. Convention aussi. 
5. le trombi c'est rendu, mais c'est où sur le site? 
6. le tableau des soft
https://drive.google.com/open?id=1XRy1GBktKO8aNuQTFsr7YVXFcr3vaGbNWeY_xRQDkFk
7. chèque, réglé aussi n'est-ce pas?  
https://github.com/openfab-lab/devis-et-facturation/issues/35

**Comment by nicolasdb** [comment]
On cloture cette issue? 
Il faudrait remettre ça au propre quelque part. 
J'ai montré l'exemple en écrivant un .md sur le repo pour le bilan 2ème tranche. #21
