### ISSUE TITLE
Log Fabvélo après 16/08/2018

### ISSUE THREAD

**Issue by milenasonneveld** [openfab-lab/FabMob#4]
* PC 3 a perdu Sculptris
* PC 5 le bouton start ne fonctionne pas
* PC Dell x? a des difficultés de connecter à l'internet
* PC Thinkpad x? ne démarre plus
* pas tous les ordi's on SculptGL https://stephaneginier.com/archive/standalone/
- [ ] il faut faire un check générale

* Fabrikator 2? thermocouple n'est plus fixé
- [ ] il faut la réparer

Pour tout ça on peut faire des mini-job avec le monnaie interne.

Pour la journée du 21/07/2018 nous avons pris une rouleau de filament jaune.
- [ ] il faut le compter dans la compta

**Comment by nicolasdb** [comment]
vieux dossier.
