### ISSUE TITLE
Accounting fabmob

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/FabMob#9]
To Do list

### asap
- [x] Réunir les derniers commentaires sur les justificatifs et faire signer
- [x] Préparer la seconde lettre de créance, faire signer
- [x] envoyer ou déposer les documents à Innoviris.
@milenasonneveld est-ce que tu peux demander à Patricia par exemple, si tu la vois pour la version papier ou pdf?

---

### septembre
- [ ] préparer ma checklist compta, toutes les étapes à vérifier. 
- [ ] booker l'agenda pour faire Juillet, Aout et les notes de frais restantes
- [ ] Améliorer le workflow et les checklist pour aider à fluidifier et déléguer la compta.

**Comment by milenasonneveld** [comment]
Yorick m'informe qu'il a rentré les documents pour le rapport financier en pdf + la lettre de créance en papier @nicolasdb

**Comment by nicolasdb** [comment]
bon ben tout ça a été fait. 
je clos cette issue mais on est déjà bon pour recommencer tout ça dans 1 semaine.
